name_microservices:
  offer: OfferMicroservice
  dishes: DishesMicroservice
  workshop: WorkShopMicroservice

server:
  port: 8080

spring:
  application:
    name: GatewayMicroservice

  datasource:
    url: jdbc:postgresql://localhost:5432/gateway_db
    username: postgres
    password: postgres

    flyway:
      url: jdbc:postgresql://localhost:5432/gateway_db
      user: postgres
      password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

jwt:
  secret: $78gr43g7g8feb8we
  header_key: Authorization
  expiration: 86400
  prefix: Bearer

