CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   email VARCHAR(255),
   password VARCHAR(255),
   CONSTRAINT pk_users PRIMARY KEY (id)
);
CREATE TABLE role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_role PRIMARY KEY (id)
);
CREATE TABLE user2role (
  u2r_role_id BIGINT NOT NULL,
   u2r_user_id BIGINT NOT NULL,
   CONSTRAINT pk_user2role PRIMARY KEY (u2r_role_id, u2r_user_id)
);

ALTER TABLE user2role ADD CONSTRAINT fk_user2role_on_role FOREIGN KEY (u2r_role_id) REFERENCES role (id);

ALTER TABLE user2role ADD CONSTRAINT fk_user2role_on_user FOREIGN KEY (u2r_user_id) REFERENCES users (id);